[workspace]
members = ["src/axum_server", "src/grpc_server"]
resolver = "2"

[workspace.dependencies]
tracing = "0.1"
tracing-subscriber = "0.3"
prost = "0.12"
tonic = "0.11"
tonic-build = "0.11"
tokio = "1.37"
tokio-stream = "0.1"
